package tv.enktel.app.data.vod

import tv.enktel.app.data.db.Category
import tv.enktel.app.data.db.Movie
import tv.enktel.app.data.m3u.M3uEntry

/**
 * Turns the free public-domain playlist into movie rows.
 *
 * The app already had two ways to take in an M3U, and neither fits this one.
 * A playlist *profile* becomes the viewer's whole lineup, which would replace
 * their line rather than add to it; an *attached* playlist has its rows filed
 * as channels on purpose, because a film out of an imported file has no panel
 * behind it to fetch a poster or a plot from and would sit in the movie
 * library as an untitled row beside titles that have both.
 *
 * This playlist is neither. It is generated by `scripts/scrape-vod.mjs` and
 * published by this project, so its shape is known rather than guessed: every
 * line carries a title with the year in brackets, a group naming the kind and
 * language, and an artwork URL. That is enough to build a real movie row, so
 * these go into the movie library where a film belongs instead of into the
 * channel list where one would be lost.
 */
object FreeVodCatalog {

    /**
     * Where these rows' stream ids start.
     *
     * A panel numbers its own catalogue from small integers, and attached
     * playlists take [tv.enktel.app.data.m3u.ImportedPlaylist] range from
     * 9,000,000,000 up. This sits below that and far above anything a panel
     * issues, so a free title can never overwrite a paid one — the row key is
     * `profileId:streamId` and a collision would silently replace a film the
     * viewer is paying for.
     */
    const val STREAM_ID_BASE = 8_000_000_000L

    /**
     * Ceiling on how many titles are taken from one playlist.
     *
     * The published catalogue is around a thousand and the whole file is
     * parsed in memory before any of it is written. This is the guard against
     * a future run — or a redirect to something else entirely — turning a sync
     * into an out-of-memory kill on a 1 GB stick.
     */
    const val MAX_TITLES = 20_000

    /** `Some Film (1935)` → `Some Film` + 1935. */
    private val TRAILING_YEAR = Regex("""\s*\((\d{4})\)\s*$""")

    /**
     * Split a trailing year off a title.
     *
     * The year is worth having as its own field — it is what the library sorts
     * and filters on — and leaving it glued to the name makes every title sort
     * as text and read as duplicated once the year is shown beside it.
     *
     * Only a four-digit year in brackets at the very end counts. Films with a
     * year in the middle of the name, or a bracketed something-else, keep
     * their name whole rather than being trimmed on a guess.
     */
    fun titleAndYear(raw: String): Pair<String, Int> {
        val name = raw.trim()
        val m = TRAILING_YEAR.find(name) ?: return name to 0
        val year = m.groupValues[1].toIntOrNull() ?: return name to 0
        // A "year" outside the range of cinema is part of the title, not a
        // date: `Apollo 13 (1970)` is a film, `Blade Runner (2049)` is not a
        // release year and neither is `Studio (1080)`.
        if (year < 1870 || year > 2100) return name to 0
        val stripped = name.removeRange(m.range).trim()
        // `(1935)` on its own is a title of nothing once the year is taken
        // out, so keep the original rather than storing a blank name.
        return if (stripped.isEmpty()) name to year else stripped to year
    }

    /** The category a title is filed under; falls back when the group is blank. */
    fun categoryFor(group: String): String =
        group.trim().ifEmpty { "Public Domain" }

    /**
     * Movie rows for [entries], in playlist order.
     *
     * Entries with no URL are dropped — a row that cannot be played is worse
     * than a missing one, because it looks like a film until it is opened.
     */
    fun movies(profileId: Long, entries: List<M3uEntry>, firstSeenAt: Long): List<Movie> =
        entries.asSequence()
            .filter { it.url.isNotBlank() }
            .take(MAX_TITLES)
            .mapIndexed { i, e ->
                val (title, year) = titleAndYear(e.name)
                val streamId = STREAM_ID_BASE + i
                Movie(
                    key = "$profileId:$streamId",
                    profileId = profileId,
                    streamId = streamId,
                    name = title,
                    poster = e.logo,
                    categoryId = categoryFor(e.group),
                    url = e.url,
                    year = year,
                    // The playlist points straight at a file rather than at a
                    // panel endpoint that needs an extension appended, so the
                    // real one is already on the URL — but only in its last
                    // path segment. Reading the whole URL finds the dot in the
                    // hostname and calls "archive.org/download/x/y" an `org/`
                    // file.
                    ext = extensionOf(e.url),
                    firstSeenAt = firstSeenAt,
                )
            }
            .toList()

    /**
     * The file extension a URL ends in, or `mp4` when it names none.
     *
     * Only the last path segment is considered: every host has a dot in it, so
     * a URL with no extension at all otherwise yields the tail of its domain.
     */
    private fun extensionOf(url: String): String {
        val path = url.substringBefore('?').substringBefore('#')
        val last = path.substringAfterLast('/')
        if (!last.contains('.')) return "mp4"
        val ext = last.substringAfterLast('.')
        // A video extension is short, alphanumeric, and contains a letter:
        // mp4, m4v, webm, ogv, mkv, ts. A dot in a filename is not a type —
        // "Film.Part.2" is not a `2` file.
        val plausible = ext.length in 2..4 &&
            ext.all { it.isLetterOrDigit() } &&
            ext.any { it.isLetter() }
        return if (plausible) ext.lowercase() else "mp4"
    }

    /** The `vod` categories those rows need, deduplicated, in first-seen order. */
    fun categories(profileId: Long, entries: List<M3uEntry>): List<Category> =
        entries.asSequence()
            .filter { it.url.isNotBlank() }
            .take(MAX_TITLES)
            .map { categoryFor(it.group) }
            .distinct()
            .mapIndexed { i, name ->
                Category(
                    key = "$profileId:vod:$name",
                    profileId = profileId,
                    kind = "vod",
                    categoryId = name,
                    name = name,
                    sortIdx = i,
                )
            }
            .toList()
}
